Repository oreotabetai/user-auth-jwt-python-api, pull requests merged in 2020-10, with the labels that each got.

#12 Create LICENSE
  LICENSE
Labels: enhancement

#15 fix dockerfile
  Dockerfile
  docker-compose.yml
  requirements.txt
Labels: fix

#16 Add GitHub Workflow for Container Build Test
  .github/workflows/ci.yml
Labels: enhancement

#17 Fix Environments
  .github/workflows/ci.yml
  docker-compose.yml
Labels: bug

#18 Add Workflow for Continuous Deploy
  .github/workflows/cd.yml
Labels: enhancement

#20 Fix CD Workflow
  .github/workflows/cd.yml
Labels: bug

#19 install uvicorn
  Dockerfile
  requirements.txt
  server.py
Labels: enhancement
